# Use uma imagem base do Python
FROM python:3.11
# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app
# Copie o arquivo requirements.txt para o diretório de trabalho
COPY ./requirements.txt .
# Instale as dependências do projeto
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pytest
# Copie todo o conteúdo do diretório atual para o diretório de trabalho no contêiner
COPY . .
# Defina o comando padrão para rodar os testes com pytest
CMD ["pytest"]


#sudo docker build -t test_application_score -f Dockerfile.test .
#docker run test_application_score